/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component.Admin;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class ManageBatch extends javax.swing.JPanel {
    
    final private String username = "root";
    final private String password = "";
    final private String database_name = "quiz";
    final private String table_name = "managebatch";
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    ResultSetMetaData metaData;

    /**
     * Creates new form ManageBatch
     */
    public ManageBatch() {
        initComponents();
        tableRecords();
    }
    
    private void tableRecords(){
        int count;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/"+database_name, username,password);
            pst = conn.prepareStatement("select * from "+table_name);
            
            rs = pst.executeQuery();
            metaData = rs.getMetaData();
            
            count = metaData.getColumnCount();
            
            DefaultTableModel dtm = (DefaultTableModel) tableBatch.getModel();
            dtm.setRowCount(0);
            
            while(rs.next()){
                Vector v = new Vector();
                for(int i = 0; i <= count; i++){
                    v.add(rs.getString("id"));
                    v.add(rs.getString("batch"));
                    v.add(rs.getString("strength"));
                }
                dtm.addRow(v);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageBatch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBatch = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textBName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textBStrength = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        tableBatch.setBackground(new java.awt.Color(255, 255, 204));
        tableBatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Batch", "Strength"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBatchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBatch);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 413;
        gridBagConstraints.ipady = 570;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(44, 48, 67, 0);
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Batch Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 185;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(96, 64, 0, 51);
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 201;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 64, 0, 51);
        add(textBName, gridBagConstraints);

        btnEdit.setBackground(new java.awt.Color(255, 255, 204));
        btnEdit.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 137, 0, 0);
        add(btnEdit, gridBagConstraints);

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 137, 0, 0);
        add(btnAdd, gridBagConstraints);

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 137, 0, 0);
        add(btnDelete, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Batch Strength");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 64, 0, 51);
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 201;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 64, 0, 51);
        add(textBStrength, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        DefaultTableModel dtm  = (DefaultTableModel) tableBatch.getModel();
        int index = tableBatch.getSelectedRow();
        String batch = textBName.getText();
        int strength = Integer.parseInt(textBStrength.getText());
        try {
            int id = Integer.parseInt(dtm.getValueAt(index, 0).toString());
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/"+database_name, username,password);
            pst = conn.prepareStatement("update "+ table_name +" set batch = ?,strength = ? where id =? ");
            pst.setString(1, batch);
            pst.setInt(2, strength);
            pst.setInt(3, id);
            pst.executeUpdate();
            
            textBName.setText("");
            textBStrength.setText("");
            textBName.requestFocus();
            tableRecords();
            JOptionPane.showMessageDialog(this, "Batch Updated Successfully...." );
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageQuiz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String batch = textBName.getText();
        int strength = Integer.parseInt(textBStrength.getText());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/"+database_name, username,password);
            pst = conn.prepareStatement("insert into "+ table_name +"(batch,strength) values(?,?)");
            pst.setString(1, batch);
            pst.setInt(2, strength);
            pst.executeUpdate();
            
            textBName.setText("");
            textBStrength.setText("");
            textBName.requestFocus();
            tableRecords();
            JOptionPane.showMessageDialog(this, "Batch Added Successfully...." );
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageQuiz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel dtm  = (DefaultTableModel) tableBatch.getModel();
        int index = tableBatch.getSelectedRow();
        
        try {
            int id = Integer.parseInt(dtm.getValueAt(index, 0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/"+database_name, username,password);
            pst = conn.prepareStatement("delete from "+table_name+" where id =? ");
            pst.setInt(1, id);
            pst.executeUpdate();
            
            textBName.setText("");
            textBStrength.setText("");
            textBName.requestFocus();
            tableRecords();
            JOptionPane.showMessageDialog(this, "Batch Deleted Successfully...." );
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageQuiz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableBatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBatchMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tableBatch.getModel();
        int index = tableBatch.getSelectedRow();
        textBName.setText(dtm.getValueAt(index, 1).toString());
        textBStrength.setText(dtm.getValueAt(index, 2).toString());
    }//GEN-LAST:event_tableBatchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBatch;
    private javax.swing.JTextField textBName;
    private javax.swing.JTextField textBStrength;
    // End of variables declaration//GEN-END:variables
}
